# name: Auto-comment on help label
# on:
#   issues:
#     types: [labeled]
# jobs:
#   auto-comment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install
#       - name: Auto-comment
#         uses: peter-evans/auto-comment@v1.5.0
#         with:
#           issue-token: 1
#           repo-token: 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
#           enable-issue-token: true
#           enable-repo-token: true
#           reactions: '+1'
#           body: |
#             Thanks for raising this issue! If you need help, please let us know and we'll do our best to assist you.
#         if: contains(github.event.issue.labels.*.name, 'help-wanted')



 name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
